#!/usr/bin/env python3

DEFAULT_CONSTANTS = {
    'TICK_WIDTH' : 1,
    'ELEVATION_UNITS_AVAILABLE' : 'true',
}

DEVICES = {
    "d2charlie"         : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "d2delta"           : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "d2deltapx"         : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "d2deltas"          : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "descentmk1"        : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix5"            : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix5plus"        : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix5s"           : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix5splus"       : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix5x"           : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix5xplus"       : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fenixchronos"      : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fr55"              : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 2}},
    "fr645"             : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fr645m"            : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "fr935"             : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 3}},
    "venusq"            : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 2}},
    "venusqm"           : {'labels' : 'short', 'constants' : {'TICK_WIDTH' : 2}},

    "approachs60"       : {'labels' : 'mid',   'constants' : {'TICK_WIDTH' : 3}},
    "fenix843mm"        : {'labels' : 'mid'},
    "fenix847mm"        : {'labels' : 'mid'},
    "fenixe"            : {'labels' : 'mid'},
    "fr165"             : {'labels' : 'mid'},
    "fr165m"            : {'labels' : 'mid'},
    "fr265"             : {'labels' : 'mid'},
    "fr265s"            : {'labels' : 'mid', 'constants' : {'TICK_WIDTH' : 2}},
    "fr955"             : {'labels' : 'mid', 'constants' : {'TICK_WIDTH' : 2}},
    "fr965"             : {'labels' : 'mid'},
    "vivoactive3"       : {'labels' : 'mid', 'constants' : {'TICK_WIDTH' : 2}},
    "vivoactive3d"      : {'labels' : 'mid', 'constants' : {'TICK_WIDTH' : 2}},
    "vivoactive3m"      : {'labels' : 'mid', 'constants' : {'TICK_WIDTH' : 2}},
    "vivoactive3mlte"   : {'labels' : 'mid', 'constants' : {'TICK_WIDTH' : 2}},
    "vivoactive5"       : {'labels' : 'mid', 'constants' : {'ELEVATION_UNITS_AVAILABLE' : 'false'}},
    "venu3"             : {'labels' : 'mid'},
    "venu3s"            : {'labels' : 'mid'},

    "approachs62"       : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "approachs7042mm"   : {'labels' : 'long'},
    "approachs7047mm"   : {'labels' : 'long'},
    "d2air"             : {'labels' : 'long'},
    "d2airx10"          : {'labels' : 'long'},
    "d2mach1"           : {'labels' : 'long'},
    "descentmk2"        : {'labels' : 'long'},
    "descentmk2s"       : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "descentmk343mm"    : {'labels' : 'long'},
    "descentmk351mm"    : {'labels' : 'long'},
    "enduro"            : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "enduro3"           : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "epix2"             : {'labels' : 'long'},
    "epix2pro42mm"      : {'labels' : 'long'},
    "epix2pro47mm"      : {'labels' : 'long'},
    "epix2pro51mm"      : {'labels' : 'long'},
    "fenix6"            : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "fenix6pro"         : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "fenix6s"           : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "fenix6spro"        : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "fenix6xpro"        : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "fenix7"            : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix7pro"         : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix7pronowifi"   : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix7s"           : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix7spro"        : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix7x"           : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix7xpro"        : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix7xpronowifi"  : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix8solar47mm"   : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fenix8solar51mm"   : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr245"             : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr245m"            : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr255"             : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr255m"            : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr255s"            : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr255sm"           : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr735xt"           : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "fr745"             : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr945"             : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "fr945lte"          : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "legacyherocaptainmarvel"   : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "legacyherofirstavenger"    : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "legacysagadarthvader"      : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "legacysagarey"     : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marq2"             : {'labels' : 'long'},
    "marq2aviator"      : {'labels' : 'long'},
    "marqadventurer"    : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marqathlete"       : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marqaviator"       : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marqcaptain"       : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marqcommander"     : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marqdriver"        : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marqexpedition"    : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "marqgolfer"        : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "venu"              : {'labels' : 'long'},
    "venu2"             : {'labels' : 'long'},
    "venu2plus"         : {'labels' : 'long'},
    "venu2s"            : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 2}},
    "venud"             : {'labels' : 'long'},
    "vivoactive4"       : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
    "vivoactive4s"      : {'labels' : 'long', 'constants' : {'TICK_WIDTH' : 3}},
}

def models_shortlabels():
    return [key for key, value in DEVICES.items() if value['labels'] == 'short']

def models_midlabels():
    return [key for key, value in DEVICES.items() if value['labels'] == 'mid']

def models_longlabels():
    return [key for key, value in DEVICES.items() if value['labels'] == 'long']

def models_all():
    return list(DEVICES.keys())